# Generated by Django 4.2.2 on 2023-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_length', models.FloatField()),
                ('component_weight', models.FloatField()),
                ('rod_weight', models.FloatField()),
                ('rod_length', models.FloatField()),
                ('scrap_value', models.FloatField(null=True)),
            ],
        ),
    ]
